assignment-5/app-5/config/routes.rb
Rails.application.routes.draw do
    
  resources :sessions
  resources :users 
  resources :posts

  resources :users, only: [] do
    resources :posts, only: [:index]
  
  end

  get "/signin" => "sessions#new"
  post "/signin" =>  "sessions#create"
  get "/signout" => "sessions#destroy"

  get '/' => "home#index", as: :home_page
end

assignment-5/app-5/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

assignment-5/app-5/app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

assignment-5/app-5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user

  def current_user
  	@current_user ||=User.find(session[:user_id])
  end


end

assignment-5/app-5/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

assignment-5/app-5/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:user_id].present?
      @posts = User.find(params[:user_id]).posts
    else
      @posts = Post.all
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(user_params)
      flash[:notice] = "Post updated!"
      redirect_to post_path(@post)
    else
      flash[:notice] = "Failed to update post"
      redirect_to edit_post_path(@post)
    end

  end

  def create
    @post = current_user.posts.create( post_params )

    if @post 
      flash[:alert] = "Posted successfully!"
      redirect_to post_path(@post) 
    else
      flash[:alert] = "Oops! Something went wrong!"
      redirect_to new_post_path
    end
  end

  def destroy
      @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post deleted successfully."
    else
      flash[:alert] = "There was a problem."
    end
    redirect_to new_post_path
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).
      permit(:post_text)
  end

end

assignment-5/app-5/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    @user = User.where(email: params[:email] ).first

    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      flash[:notice] = "Signed in!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Email or password is incorrect"
      redirect_to signin_path
    end

  end

  def destroy
  	session[:user_id] = nil
    redirect_to home_page_path
  end

  private
  def user_params
  	params.require(:user).
  		permit(:email, :password)
  end


end

assignment-5/app-5/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:notice] = "User updated"
      redirect_to user_path(@user)
    else
      flash[:notice] = "Failed to update user"
      redirect_to edit_user_path(@user)
    end
  end

  def create
    @user = User.create( user_params )

    if @user 
      flash[:alert] = "Signed up successfully"
      redirect_to user_path(@user) 
    else
      flash[:alert] = "Oops! Something went wrong"
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "User deleted successfully."
    else
      flash[:alert] = "There was a problem."
    end
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).
      permit(:first_name, :last_name, :email, :password)
  end
end

assignment-5/app-5/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment-5/app-5/app/helpers/home_helper.rb
module HomeHelper
end

assignment-5/app-5/app/helpers/posts_helper.rb
module PostsHelper
end

assignment-5/app-5/app/helpers/sessions_helper.rb
module SessionsHelper
end

assignment-5/app-5/app/helpers/users_helper.rb
module UsersHelper
end

assignment-5/app-5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>

<%= yield %>

</body>
</html>

assignment-5/app-5/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

assignment-5/app-5/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

assignment-5/app-5/app/views/posts/edit.html.erb
<h1>Edit Your Post</h1>

<%= form_for @post do |f| %>
	<p>
	<%= f.label :post_text %>
	<%= f.text_area_tag :post_text, :size =>"25x10" %>
	</p>
	<p> <%= link_to "Delete post", post_path, method: :delete %>
	</p>
	<p>
	<%= f.submit %>
	</p>

<% end %>

assignment-5/app-5/app/views/posts/index.html.erb
<h1>Posts</h1>
<hr>
<% @posts.each do |post| %>
	<div>
		<p>
			<%= post.post_text %>
		</p>

		<p>
			<% if post.user %>
				<%= post.user.first_name %>
				<%= post.user.last_name %>
			<% end %>
		</p>

		<p>
			<%= link_to "Edit", edit_post_path(post) %> |
			<%= link_to "Delete", post_path(post), method: :delete %>
		</p>	
	</div>
	<hr>
<% end %>

assignment-5/app-5/app/views/posts/new.html.erb
<!-- "Logged in as @user" or "Sign in to post" -->

<h1>Write a new post</h1>

<%= form_for @post do |f| %>
		<p>
	<%= f.label :post_text %>
	<%= f.text_field :post_text %>
	</p>
	<p>
	<%= f.submit %>
	</p>

<% end %>

assignment-5/app-5/app/views/posts/show.html.erb
<h1>View single post</h1>
<p>
	<%= @post.post_text %>	
</p>

<p>
	<%= link_to "View all posts", posts_path %>
</p>

assignment-5/app-5/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

assignment-5/app-5/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

assignment-5/app-5/app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= form_for @user do |f| %>
	<p>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	</p>
	<p>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>	
	</p>
	<p>
	<%= f.label :email %>
	<%= f.text_field :email %>	
	</p>
	<p>
	<%= f.label :password %>
	<%= f.password_field :password %>	
	</p>
	<p>
	<%= f.submit %>
	</p>

<% end %>

assignment-5/app-5/app/views/users/index.html.erb
<h1>Users</h1>
<hr>
<% @users.each do |user| %>
	<div>
		<p>
			<%= link_to "#{user.first_name} #{user.last_name}", post_path(user) %>
		</p>
	</div>
<% end %>

assignment-5/app-5/app/views/users/new.html.erb
<h1>Sign Up for App-5 Blog</h1>

<%= form_for @user do |f| %>
	<p>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	</p>
	<p>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>	
	</p>
	<p>
	<%= f.label :email %>
	<%= f.text_field :email %>	
	</p>
	<p>
	<%= f.label :password %>
	<%= f.password_field :password %>	
	</p>
	<p>
	<%= f.submit %>
	</p>

<% end %>

assignment-5/app-5/app/views/users/show.html.erb
<h1>Profile Page for
<%= @user.first_name %></h1>
<hr>
<p>
	<%= @user.first_name %>
	<%= @user.last_name %>	
</p>

<p>
	<%= mail_to @user.email %>
</p>

<p>
	<%= link_to "Edit", edit_user_path(@user) %> |
	<%= link_to "Delete", user_path(@user), method: :delete %>
</p>

<p>
	<%= link_to "Posts by this user", user_posts_path(@user) %> |
	<%= link_to "Create a post", new_post_path %>
</p>


<p>
	<%= link_to "Sign out", signout_path %>
</p>