assignment-2/app-2/config/routes.rb
Rails.application.routes.draw do

 # resources :user

  get '/users' => "user#index" 
  get '/user/profile' => "user#profile" 
  get '/search' => "home#search", as: :search_page
  get '/' => "home#index", as: :home_page

end

assignment-2/app-2/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def search
	end

end

assignment-2/app-2/app/controllers/user_controller.rb
class UserController < ApplicationController

	def index
	#	@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def profile
		
	end
end

assignment-2/app-2/app/helpers/user_helper.rb
module UserHelper
end

assignment-2/app-2/app/views/home/_menu.html.erb
<div style= "float:left; width:20%;">
<hr />
<h2>App Menu</h2>
<p><%= link_to "View users page", users_path %></p>
<p><%= link_to "View user profile page", user_profile_path %></p>
<p><%= link_to "View search page", search_page_path %></p>
<p><%= link_to "View on GitHub", "https://github.com/monsterbash/nycda-rails/tree/master/assignment-1" %></p>
<hr />
</div>

assignment-2/app-2/app/views/home/index.html.erb
<div style="float:left; width:80%;">
<h1>Assignment 2 App Homepage </h1>
<h2>Welcome to the Assignment 2 App</h2>
<p>This assignment is an app made with two controllers, which each include two views.<br /> The menu on this page is rendered using a partial.</p>
</div>

<%= render "menu" %>

assignment-2/app-2/app/views/home/search.html.erb
<h1>Search Page </h1>
<p>If there were a search function, the results would display on this page.<br />This is the second view in the home controller</p>

<p><%= link_to "Return to home page", home_page_path %></p>

assignment-2/app-2/app/views/user/index.html.erb
<h1>All Users Page </h1>

<p>This page would list all the users.<br /> This is the first view in the user controller.</p>

<p><%= link_to "Return to home page", home_page_path %></p>
<p><%= link_to "View user profile page", user_profile_path %></p>

assignment-2/app-2/app/views/user/profile.html.erb
<h1>User Profile Page </h1>

<p>This page would show one user's profile.<br /> This is the second view in the user controller.</p>


<p><%= link_to "Return to users page", users_path %></p>
<p><%= link_to "Return to home page", home_page_path %></p>